DapperCv.WebUI/Areas/Admin/Controllers/ExperienceController.cs
using AutoMapper;
using DapperCv.Business.Interfaces;
using DapperCv.DTO.DTOs.ExperienceDtos;
using DapperCv.DTO.DTOs.InterestDtos;
using DapperCv.Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DapperCv.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Developer")]
    public class ExperienceController : Controller
    {

        private readonly IGenericService<Experience> _exService;
        private readonly IMapper _mapper;

        public ExperienceController(IGenericService<Experience> exService, IMapper mapper)
        {
            _exService = exService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            TempData["active"] = "experience";
            return View(_mapper.Map<List<ExperienceListDto>>(_exService.GetAll()));
        }

        public IActionResult Delete(int id)
        {
            TempData["active"] = "experience";

            var model = _exService.GetById(id);
            _exService.Delete(model);

            TempData["message"] = "Tecrübe Bilgisi Başarıyla Silindi";

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Add()
        {
            TempData["active"] = "experience";
            return View(new ExperienceAddDto());
        }

        [HttpPost]
        public IActionResult Add(ExperienceAddDto model)
        {
            TempData["active"] = "experience";
            if (ModelState.IsValid)
            {
                _exService.Insert(_mapper.Map<Experience>(model));
                TempData["message"] = "Tecrübe Bilgisi Başarıyla Eklendi";
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            TempData["active"] = "experience";
            var model = _mapper.Map<ExperienceUpdateDto>(_exService.GetById(id));
            return View(model);
        }

        [HttpPost]
        public IActionResult Update(ExperienceUpdateDto model)
        {
            TempData["active"] = "education";
            if (ModelState.IsValid)
            {
                _exService.Update(_mapper.Map<Experience>(model));
                TempData["message"] = "Tecrübe Bilgisi Başarıyla Güncellendi";
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

DapperCv.WebUI/Areas/Admin/Views/Experience/Add.cshtml
@model ExperienceAddDto


<div class="text-left my-2">
    <button id="end-date-add-button" class="btn btn-warning">Bitiş Tarihi Ekle</button>
    <button hidden id="end-date-delete-button" class="btn btn-danger">Bitiş Tarihini İptal Et</button>
</div>

<form asp-action="Add" method="post">
    <div class="form-group">
        <label>Title</label>
        <span class="text-danger" asp-validation-for="Title"></span>
        <input asp-for="Title" class="form-control" />
    </div>
    <div class="form-group">
        <label>Sub Title</label>
        <span class="text-danger" asp-validation-for="SubTitle"></span>
        <input asp-for="SubTitle" class="form-control" />
    </div>
    <div class="form-group">
        <label>Açıklama</label>
        <span class="text-danger" asp-validation-for="Description"></span>
        <input asp-for="Description" class="form-control" />
    </div>
    <div class="form-group">
        <label>Başlangıç</label>
        <span class="text-danger" asp-validation-for="StartDate"></span>
        <input asp-for="StartDate" class="form-control" />
    </div>

    <div class="form-group" id="submit-button">
        <button type="submit" class="btn btn-primary">Kaydet</button>
    </div>
</form>

@section Scripts{

    <script>

        $("#end-date-add-button").click(function () {
            $("#submit-button").before('<div class="form-group" id="end-date"><label>Bitiş</label><span class="text-danger field-validation-valid" data-valmsg-for="EndtDate" data-valmsg-replace="true"></span><input class="form-control" type="datetime-local" data-val="true" data-val-required="Bitiş Tarihi Boş Olamaz" id="EndDate" name="EndDate" value="0001-01-01T00:00:00.000"></div>');
            $(this).attr("hidden",true);
            $("#end-date-delete-button").removeAttr("hidden");
        });

        $("#end-date-delete-button").click(function () {
            $("#end-date").remove();
            $(this).attr("hidden", true);
            $("#end-date-add-button").removeAttr("hidden");
        });
    </script>


}

DapperCv.WebUI/Areas/Admin/Views/Experience/Index.cshtml
@model List<ExperienceListDto>

<div class="text-right my-2">
    <a asp-action="Add" class="btn btn-outline-dark">Add Experience</a>
</div>
<table class="table table-hover table-striped table-bordered table-sm">
    <thead>
        <tr>
            <th>Title</th>
            <th>Sub Title</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Description</th>
            <th>İşlem</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.Title</td>
            <td>@item.SubTitle</td>
            <td>@item.StartDate</td>
            <td>
                @{
                    if (item.EndDate == null)
                    {
                        <span>Present</span>
                    }
                    else
                    {
                        <span>@item.EndDate</span>
                    }
                }

            </td>
            <td>@item.Description</td>
            <td>
                <a class="btn btn-success btn-sm" asp-action="Update" asp-controller="Experience" asp-route-id="@item.Id">Güncelle</a>
                <a class="btn btn-danger btn-sm" onclick="return confirm('Emin misiniz?')" asp-action="Delete" asp-controller="Experience" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>


</table>

DapperCv.WebUI/Areas/Admin/Views/Experience/Update.cshtml
@model ExperienceUpdateDto


<div class="text-left my-2">
    <button hidden id="end-date-add-button" class="btn btn-warning">Bitiş Tarihi Ekle</button>
    <button hidden id="end-date-delete-button" class="btn btn-danger">Bitiş Tarihini İptal Et</button>
</div>

<form asp-action="Update" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label>Title</label>
        <span class="text-danger" asp-validation-for="Title"></span>
        <input asp-for="Title" class="form-control" />
    </div>
    <div class="form-group">
        <label>Sub Title</label>
        <span class="text-danger" asp-validation-for="SubTitle"></span>
        <input asp-for="SubTitle" class="form-control" />
    </div>
    <div class="form-group">
        <label>Açıklama</label>
        <span class="text-danger" asp-validation-for="Description"></span>
        <input asp-for="Description" class="form-control" />
    </div>
    <div class="form-group">
        <label>Başlangıç</label>
        <span class="text-danger" asp-validation-for="StartDate"></span>
        <input asp-for="StartDate" class="form-control" />
    </div>
    @if (Model.EndDate != null)
    {
        <div class="form-group" id="end-date">
            <label>Bitiş</label>
            <span class="text-danger" asp-validation-for="EndDate"></span>
            <input asp-for="EndDate" class="form-control" />
        </div>
    }

    <div class="form-group"  id="submit-button">
        <button type="submit" class="btn btn-primary">Kaydet</button>
    </div>
</form>

@section Scripts{

    <script>

        var control = function () {
            var count = $('#end-date').length;
            if (count>0) {
                $("#end-date-delete-button").removeAttr("hidden");
            }
            else {
                $("#end-date-add-button").removeAttr("hidden");
            }
        };

        control();

        $("#end-date-add-button").click(function () {
            $("#submit-button").before('<div class="form-group" id="end-date"><label>Bitiş</label><span class="text-danger field-validation-valid" data-valmsg-for="EndtDate" data-valmsg-replace="true"></span><input class="form-control" type="datetime-local" data-val="true" data-val-required="Bitiş Tarihi Boş Olamaz" id="EndDate" name="EndDate" value="0001-01-01T00:00:00.000"></div>');
            $(this).attr("hidden",true);
            $("#end-date-delete-button").removeAttr("hidden");
        });

        $("#end-date-delete-button").click(function () {
            $("#end-date").remove();
            $(this).attr("hidden", true);
            $("#end-date-add-button").removeAttr("hidden");
        });
    </script>


}