DapperCv.WebUI/Areas/Admin/Controllers/SkillController.cs
using AutoMapper;
using DapperCv.Business.Interfaces;
using DapperCv.DTO.DTOs.SkillsDtos;
using DapperCv.Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DapperCv.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Developer")]
    public class SkillController : Controller
    {

        private readonly IGenericService<Skill> _skillService;
        private readonly IMapper _mapper;

        public SkillController(IGenericService<Skill> skillService, IMapper mapper)
        {
            _skillService = skillService;
            _mapper = mapper;
        }

     

        public IActionResult Index()
        {
            TempData["active"] = "skill";
            return View(_mapper.Map<List<SkillListDto>>(_skillService.GetAll()));
        }

        public IActionResult Delete(int id)
        {
            var model = _skillService.GetById(id);
            _skillService.Delete(model);
            TempData["message"] = "Yetenek Başarıyla Silindi";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Add()
        {
            TempData["active"] = "skill";
            return View(new SkillAddDto());
        }

        [HttpPost]
        public IActionResult Add(SkillAddDto model)
        {
            TempData["active"] = "skill";

            if (ModelState.IsValid)
            {
                var skill = _mapper.Map<Skill>(model);
                _skillService.Insert(skill);
                TempData["message"] = "Yetenek Başarıyla Kaydedildi";
                return RedirectToAction("Index");
            }

            return View();
        }


        [HttpGet]
        public IActionResult Update(int id)
        {
            TempData["active"] = "skill";
            var skill = _skillService.GetById(id);
            var model = _mapper.Map<SkillUpdateDto>(skill);
            return View(model);
        }

        [HttpPost]
        public IActionResult Update(SkillUpdateDto model)
        {
            TempData["active"] = "skill";

            if (ModelState.IsValid)
            {
                var skill = _mapper.Map<Skill>(model);
                _skillService.Update(skill);
                TempData["message"] = "Yetenek Başarıyla Düzenlendi";
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

DapperCv.WebUI/Areas/Admin/Views/Skill/Add.cshtml
@model SkillAddDto

<form asp-action="Add" method="post">
    <div class="form-group">
        <label>Yetenek Bilgisi</label>
        <span class="text-danger" asp-validation-for="Description"></span>
        <input asp-for="Description" class="form-control" />
    </div>
    <div class="form-group">
        <label>Yetenek İkonu</label>
        <span class="text-danger" asp-validation-for="Icon"></span>
        <input asp-for="Icon" class="form-control" />
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Kaydet</button>
    </div>
</form>

DapperCv.WebUI/Areas/Admin/Views/Skill/Index.cshtml
@model List<SkillListDto>

<div class="text-right my-2">
    <a asp-action="Add" class="btn btn-outline-dark">Add Skill</a>
</div>
<table class="table table-hover table-striped table-bordered table-sm">
    <thead>
        <tr>
            <th>Yetenekler</th>
            <th>İşlem</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Description</td>
                <td>@item.Icon</td>
                <td>
                    <a class="btn btn-success btn-sm" asp-action="Update" asp-controller="Skill" asp-route-id="@item.Id">Güncelle</a>
                    <a class="btn btn-danger btn-sm" onclick="return confirm('Emin misiniz?')" asp-action="Delete" asp-controller="Skill" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>


</table>

DapperCv.WebUI/Areas/Admin/Views/Skill/Update.cshtml
@model SkillUpdateDto

<form asp-action="Update" method="post">

    <div class="form-group">
        <input type="hidden" asp-for="Id" />
        <label>Yetenek Alanı</label>
        <span class="text-danger" asp-validation-for="Description"></span>
        <input asp-for="Description" class="form-control" />
    </div>

    <div class="form-group">
        <label>İkon Alanı</label>
        <span class="text-danger" asp-validation-for="Icon"></span>
        <input asp-for="Icon" class="form-control" />
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Kaydet</button>
    </div>
</form>